// 1807/wcy/src/views/Guide.vue
<template>
    <div class="guide">
        <mt-swipe 
        v-bind:auto="4000"
        :show-indicators="false"
        >
            <mt-swipe-item v-for="(img,index) in imgs" :key="index"  >
                <img @click="gotoIndex(index)" v-bind:src="img" alt="" class="img">
            </mt-swipe-item>
        </mt-swipe>
    </div>
</template>


<script>
export default {
    data(){
        return {
            imgs:[
                require("../assets/images/slide1.png"),
                require("../assets/images/slide2.png"),
                require("../assets/images/slide3.png"),
                require("../assets/images/slide4.png"),
            ]
        }
    },
    methods:{
        gotoIndex(index){
            
            if(index==this.imgs.length-1){
                this.$router.push("/app/")
            }
        }
    },
    mounted(){
        if(localStorage.pcount){
            this.$router.push("/app/")
        }else{
            localStorage.pcount = 1;
        }
    }

}
</script>

<style scoped>
.guide , .mint-swipe ,.img{
    width:100%;
    height:100%;
}

</style>

// 1807/react-reduxTest/src/scripts/redux/views/guide/index.js

import "./index.scss";
import React, { Component } from "react";

import SwiperDemo from "../../../components/swiper"

export default class Guide extends Component{

    state={
        img:[
            require("../../../../assets/images/slide1.png"),
            require("../../../../assets/images/slide2.png"),
            require("../../../../assets/images/slide3.png"),
            require("../../../../assets/images/slide4.png"),
        ]
    }
    gotoApp = (index) => {
        console.log(index)
        let { history } = this.props;
        if (index == this.state.img.length-1) {
            history.push("/app/")
        }
    }
    componentWillMount(){
        let { history } = this.props;
        if (localStorage.visitCount){
            if (localStorage.visitCount >= 3) {
                localStorage.visitCount++;
                history.push("/app/")
            } else {
                localStorage.visitCount++;
            }
        }else{
            localStorage.visitCount=1
        }
    }


    render(){
        let images=this.state.img.map((img,index)=>{
            return (
                <img onClick={() => this.gotoApp(index)} className='img' key={index} src={img} alt=""/>
            )
        })
        return(
            <div className='box'>
                <SwiperDemo id="guide" swiperOptions={{ speed: 1200}}>
                    {images}
                </SwiperDemo>
            </div>
        )
    }
}
